name: satagro
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  data_table_2: 2.5.15
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_maps_flutter: ^2.9.0
  hooked_bloc: ^1.5.0
  injectable: ^2.5.0
  meta: ^1.15.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
